language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y check
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y git

install:
- git clone git://github.com/OpenPTV/openptv.git
- cd openptv/liboptv
- mkdir _build && cd _build
- cmake ../
- make
- make verify
- sudo make install

