language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND="nosetests {project}/tests"
    - TWINE_USERNAME=alexlib
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - sudo $PIP install https://github.com/joerick/cibuildwheel/archive/master.zip twine
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      twine upload wheelhouse/*.whl
    fi
